# Site settings
title: OHI-Science Subcountry Status
email: ohi-science@nceas.ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  Ocean Health Index status of subcountry repositories.
baseurl: "subcountry" # the subpath of your site, e.g. /blog/
url: "http://ohi-science.org" # the base hostname & protocol for your site
twitter_username: OceanHealthIndx
github_username:  OHI-Science

# Build settings
markdown: kramdown
kramdown:
  input:         GFM
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false
  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      nil
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
highlighter: pygments
